- name: user creation roboshop
  hosts: local
  connectionns: local
  tasks:
  - name: check roboshop user exits or not 
    ansible.builtin.command: id roboshop
    ignore_errors: true 

  - name: create user
    become: yes
    ansible.builtin.command: useradd roboshop
    register: output
    when: ouput.rc !=0 #if any error then exit here 

  - name: user already exits 
    ansible.buitlin.debug: 
      msg: " user already exits "
    when: output.rc ==0 #user already exits run this 
