---
- name: Destroy EC2 and Route53 records
  hosts: local
  connection: local

  vars:
    instances:
      - mysql
      - backend
      - frontend
    zone: kodari.online

  tasks:

    - name: Delete Route53 records
      amazon.aws.route53:
        state: absent
        zone: "{{ zone }}"
        record: "{{ item }}.{{ zone }}"
        type: A
      loop: "{{ instances }}"

    - name: Delete main domain record
      amazon.aws.route53:
        state: absent
        zone: "{{ zone }}"
        record: "{{ zone }}"
        type: A

    - name: Terminate EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        state: absent
      loop: "{{ instances }}"